USE [master]
GO

/****** Object:  Database [AvisTesteMVC]   ******/
CREATE DATABASE [AvisTesteMVC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AvisTesteMVC', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.LOCALSQLSERVER\MSSQL\DATA\AvisTesteMVC.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AvisTesteMVC_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.LOCALSQLSERVER\MSSQL\DATA\AvisTesteMVC_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AvisTesteMVC] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AvisTesteMVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AvisTesteMVC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET ARITHABORT OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AvisTesteMVC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AvisTesteMVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AvisTesteMVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AvisTesteMVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AvisTesteMVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AvisTesteMVC] SET  MULTI_USER 
GO

ALTER DATABASE [AvisTesteMVC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AvisTesteMVC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AvisTesteMVC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AvisTesteMVC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AvisTesteMVC] SET  READ_WRITE 
GO


